# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zxhnext
brief-intro: 我的前端之旅
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zxhnext.github.io" # the base hostname & protocol for your site

permalink: none

# other links
twitter_username: zxhnext
facebook_username: zxhnext
github_username:  zxhnext
#email: xiaohannext@qq.com
weibo_username: zxhnext
zhihu_username: zxhnext
#linkedIn_username: 
#dribbble_username:

description_footer: 记录我的前端学习旅程！

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
#disqus_shortname: 
livere_shortname: zxhnext

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 3ea63191cb122e90fb9277212616bd29
google_analytics_id: UA-107855556-1 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
